
favicon: favicon.ico

avatarset: images/avatarIcons.svg


# disqus
#disqus_shortname: drakeleung

# social
social:
  github: https://github.com/jhia
  twitter: https://twitter.com/All_Jh
  linkedin: https://www.linkedin.com/in/jhiam

icons:
  github: images/GitHub.svg
  twitter: images/Twitter.svg
  linkedin: images/LinkedIn.svg

# nav #
nav:
  home: .
  all: archives
  whoami: whoami
  #rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


#google_anlytics: # Put tracking ID here
